module.exports = [
  {
    id: "industrial-piping",
    number: "01",
    title: "Industrial piping",
    titleKey: "services_grid_1",
    image: "img/pipelines2022/p11.webp",
  },
  {
    id: "process-media",
    number: "02",
    title: "Process utility systems",
    titleKey: "services_grid_2",
    image: "img/piec202301/p5.webp",
  },
  {
    id: "industrial-boiler-rooms",
    number: "03",
    title: "Industrial boiler rooms",
    titleKey: "services_grid_3",
    image: "img/ostroda202302/o23.webp",
  },
  {
    id: "heating-systems",
    number: "04",
    title: "Heating systems",
    titleKey: "services_grid_4",
    image: "img/mapress/m1.webp",
  },
  {
    id: "equipment-installation",
    number: "05",
    title: "Industrial equipment installation",
    titleKey: "services_grid_5",
    image: "img/piec202301/p7.webp",
  },
  {
    id: "equipment-relocation",
    number: "06",
    title: "Industrial equipment relocation",
    titleKey: "services_grid_6",
    image: "img/sweden202205/s7.webp",
  },
  {
    id: "welding-prefabrication",
    number: "07",
    title: "Welding and prefabrication",
    titleKey: "services_grid_7",
    image: "img/azot202309/a5.webp",
  },
  {
    id: "steel-structures",
    number: "08",
    title: "Steel structures",
    titleKey: "services_grid_8",
    image: "img/cabana2021/c1.webp",
  },
  {
    id: "marine-services",
    number: "09",
    title: "Ship outfitting and modernization",
    titleKey: "services_grid_9",
    image: "img/marella202201/2m3.webp",
  },
];